# Data set de divorcios

In [18]:
import pandas as pd
divorcios = pd.read_csv("Divorcios por departamento.csv")
divorcios
# divorcios.columns

# columnas_a_eliminar = ['Unnamed: 24']  # Agrega más nombres si quieres eliminar otras
# data = divorcios.drop(columns=columnas_a_eliminar, errors='ignore')
# divorcios

,Año,República,Guatemala,El Progreso,Sacatepéquez,Chimaltenango,Escuintla,Santa Rosa,Sololá,Totonicapán,...,Huehuetenango,Quiché,Baja Verapaz,Alta Verapaz,Petén,Izabal,Zacapa,Chiquimula,Jalapa,Jutiapa
0,2022,"9,950","3,295",179,174,210,497,316,137,201,...,450,314,145,198,326,286,195,212,238,402
1,2021,"9,621","3,339",206,189,258,496,323,96,180,...,399,280,171,194,258,310,178,269,243,371
2,2020,"4,074","1,361",68,85,122,172,164,41,88,...,138,147,50,102,106,134,91,103,91,154
3,2019,"8,203","3,491",146,168,172,389,208,110,157,...,250,205,158,135,189,213,198,183,186,234
4,2018,"6,255","2,185",115,153,147,302,174,71,135,...,193,197,140,133,167,241,161,174,148,251
5,2017,"5,808","2,075",108,154,129,345,172,67,108,...,187,130,117,112,154,244,165,164,131,180
6,2016,"5,665","2,142",95,133,106,297,179,63,86,...,176,166,115,114,124,189,148,158,126,235
7,2015,"5,726","2,185",98,115,125,306,187,59,96,...,182,147,107,139,159,159,157,141,115,284
8,2014,"5,575","2,044",114,138,124,291,135,57,100,...,170,161,121,140,125,163,147,162,114,344
9,2013,"5,542","2,261",86,122,82,210,95,52,79,...,176,151,116,158,156,155,188,119,110,340
10,2012,"5,157","2,152",89,71,67,176,98,48,74,...,159,109,108,175,138,219,149,133,106,269
11,2011,"4,344","1,798",82,72,57,179,106,46,64,...,126,107,54,176,92,124,141,102,105,208
12,2010,"3,645","1,561",63,61,38,149,77,41,46,...,80,84,75,129,94,130,115,73,77,168
13,2009,"3,004","1,140",41,77,59,124,92,27,38,...,79,83,59,132,49,82,100,79,85,128
14,2008,"2,834","1,052",45,80,58,92,50,16,39,...,57,63,69,106,48,117,109,97,74,119
15,2007,"2,128","1,040",16,61,10,41,11,11,29,...,49,9,35,108,33,133,76,79,47,29
16,2006,"1,917",904,14,66,19,40,20,6,23,...,54,23,38,66,37,105,67,57,50,50
17,2005,"2,088","1,167",12,49,18,25,13,4,29,...,45,26,29,76,24,94,64,44,59,64

# Data set de Numero de denuncias de violencia intrafamiliar por tipo de agresion sufrida

In [19]:
tipo_agresion = pd.read_csv("Numero de denuncias de violencia intrafamiliar por tipo de agresion sufrida.csv")
tipo_agresion

,Año,Total,Física,Psicológica,Sexual,Patrimonial,Física - psicológica,Física - sexual,Física - patrimonial,Psicológica - sexual,Psicológica - patrimonial,Sexual - patrimonial,Física - psicológica - sexual,Física - psicológica - patrimonial,Psicológica - sexual - patrimonial,Física - sexual - patrimonial,Física - psico - sexual - patrimonial
0,2008,"23,721","3,765","6,111",49,310,"9,572",56,115,83,"1,116",1,339,"1,912",28,7,257
1,2009,"31,497","4,133","8,552",78,449,"13,371",85,127,121,"1,519",7,450,"2,305",18,10,272
2,2010,"32,017","4,177","8,145",65,296,"14,267",63,133,140,"1,326",5,445,"2,606",29,10,310
3,2011,"33,484","4,014","9,279",73,308,"14,425",61,164,128,"1,521",5,443,"2,718",41,8,296
4,2012,"36,107","3,841","10,190",72,305,"15,735",66,149,121,"1,710",4,479,"3,101",25,7,302
5,2013,"36,170","4,050","11,188",94,265,"14,741",57,108,130,"1,850",6,439,"2,962",33,7,240
6,2014,"34,330","3,632","10,864",131,222,"13,783",53,84,153,"1,835",11,383,"2,942",21,3,213
7,2015,"31,929","3,584","10,664",105,451,"12,528",62,63,154,"1,357",3,295,"2,446",21,11,185
8,2016,"31,190","3,972","10,729",101,459,"11,570",59,84,111,"1,445",2,249,"2,269",11,8,121
9,2017,"30,384","3,713","11,993",150,435,"10,363",64,63,132,"1,420",8,234,"1,667",28,6,108
10,2018,"29,992","3,483","11,968",125,428,"10,137",47,53,99,"1,631",4,186,"1,699",12,3,117
11,2019,"31,898","3,861","13,155",119,415,"10,813",57,63,121,"1,593",10,189,"1,369",16,4,113
12,2020,"28,259","3,359","11,534",110,261,"9,844",37,60,104,"1,474",2,115,"1,260",11,6,82
13,2021,"36,435","3,976","16,843",104,380,"11,370",47,61,137,"1,892",6,209,"1,279",24,14,93
14,2022,"37,194","3,735","18,004",89,356,"11,466",57,62,171,"1,729",1,171,"1,263",11,7,72

# Data set de Número de denuncias de violencia intrafamiliar por departamento

In [20]:
num_intra_dep = pd.read_csv("Número de denuncias de violencia intrafamiliar por departamento.csv")
num_intra_dep

,Año,República,Guatemala,El Progreso,Sacatepéquez,Chimaltenango,Escuintla,Santa Rosa,Sololá,Totonicapán,...,Quiché,Baja Verapaz,Alta Verapaz,Petén,Izabal,Zacapa,Chiquimula,Jalapa,Jutiapa,Ignorado
0,2008,"23,721","5,117",978,926,"1,167","1,417",495,537,616,...,769,871,"1,518",551,355,694,585,716,556,9
1,2009,"31,497","6,692","1,108","1,368","1,688","1,654","1,051",838,698,...,"1,302","1,095","2,037",759,946,854,644,766,713,91
2,2010,"32,017","5,792","1,101","1,356","1,690","1,163",953,994,686,...,"1,622","1,059","2,501",914,937,628,777,856,803,246
3,2011,"33,484","6,122","1,101","1,492","1,920","1,088",857,882,627,...,"1,676","1,031","2,639","1,090",844,682,473,"1,244","1,006",264
4,2012,"36,107","6,911","1,039","1,651","1,785","1,169","1,082","1,106",581,...,"1,180","1,151","3,120","1,049",744,654,391,"1,132","1,192",178
5,2013,"36,170","6,581","1,142","1,783","1,723",794,"1,441","1,062",571,...,741,"1,195","3,343","1,086",814,757,443,840,"1,203",279
6,2014,"34,330","5,777","1,081","1,584","1,924",569,"1,321",996,634,...,"1,158","1,265","3,253",981,672,703,465,976,"1,353",97
7,2015,"31,929","6,410",883,"1,613","1,824",451,964,646,519,...,"1,095",874,"3,485","1,295",580,606,399,732,862,43
8,2016,"31,190","6,053",675,"1,477","1,694",299,"1,040",542,486,...,"1,002",771,"3,492","1,282",584,538,429,594,"1,059",66
9,2017,"30,384","5,451",825,"1,623","1,673",374,"1,089",550,445,...,705,651,"4,240","1,087",647,706,455,698,"1,139",43
10,2018,"29,992","5,398","1,030","1,776","1,647",547,"1,224",485,394,...,575,548,"3,873",799,795,635,566,534,"1,294",32
11,2019,"31,898","5,462","1,069","1,308","1,756","1,313","1,281",519,427,...,607,833,"4,379",827,709,775,540,383,"1,161",34
12,2020,"28,259","3,379",889,"1,381","1,868","1,191","1,208",525,454,...,363,912,"3,881",794,678,867,576,357,"1,327",39
13,2021,"36,435","7,476","1,252","1,686","2,136","1,630","1,542",479,546,...,612,"1,210","4,402","1,037",902,"1,167",511,387,"1,550",84
14,2022,"37,194","8,268","1,122","1,689","2,169","1,745","1,126",355,462,...,629,"1,331","4,561","1,043",918,903,475,456,"1,245",549

# Data set de Numero de denuncias de violencia intrafamiliar por grupos quinquenales de edad

In [22]:
por_edad = pd.read_csv("Numero de denuncias de violencia intrafamiliar por grupos quinquenales de edad.csv")
por_edad

,Año,Total,0 a 4,5 a 9,10 a 14,15 a 19,20 a 24,25 a 29,30 a 34,35 a 39,40 a 44,45 a 49,50 a 54,55 a 59,60 a 64,65 y más,Ignorado
0,2008,"32,017",21,58,178,"2,211","4,354","4,707","3,937","2,787","1,925","1,196",795,457,286,486,323
1,2009,"33,484",29,43,221,"2,748","5,955","6,190","5,154","3,816","2,472","1,682","1,039",621,421,757,349
2,2010,"36,107",36,54,224,"2,979","5,974","6,187","5,441","3,826","2,508","1,663","1,002",612,423,756,332
3,2011,"36,170",38,48,223,"3,070","6,213","6,261","5,599","4,121","2,600","1,768","1,117",674,472,842,438
4,2012,"34,330",21,78,242,"3,373","6,825","6,823","6,081","4,402","2,795","1,774","1,172",702,482,877,460
5,2013,"36,170",26,50,280,"3,420","6,780","6,816","6,056","4,287","2,913","1,789","1,241",727,509,848,428
6,2014,"34,330",57,86,304,"3,316","6,275","6,367","5,648","4,166","2,747","1,721","1,114",725,538,889,377
7,2015,"31,929",44,85,275,"2,895","5,998","5,972","5,162","3,985","2,505","1,539","1,046",713,496,915,299
8,2016,"31,190",41,76,240,"2,717","5,716","5,887","5,048","3,821","2,503","1,543","1,039",715,497,885,462
9,2017,"30,384",49,83,245,"2,369","5,677","5,714","4,687","3,873","2,490","1,676","1,008",681,500,943,389
10,2018,"29,992",35,79,183,"2,286","5,623","5,517","4,727","3,762","2,550","1,518","1,068",772,527,"1,020",325
11,2019,"31,898",36,71,185,"2,281","5,720","5,944","5,029","4,030","2,847","1,707","1,119",759,610,"1,168",392
12,2020,"28,259",32,66,161,"1,899","4,933","5,220","4,649","3,550","2,460","1,600","1,050",777,542,"1,005",315
13,2021,"36,435",25,76,187,"2,045","5,935","6,608","5,887","4,684","3,503","2,152","1,460",950,803,"1,412",708
14,2022,"37,194",40,62,211,"1,897","5,694","6,609","6,002","4,760","3,577","2,383","1,600","1,078",792,"1,598",891